# Generated by Django 3.2.4 on 2021-07-12 15:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crdPost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=150, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('upcomming', 'upcomming'), ('running', 'running'), ('ended', 'ended')], max_length=20, null=True)),
                ('image', models.ImageField(upload_to='Product/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crdPost.postcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='crdOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField(null=True)),
                ('nonce', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('ph_no', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('payment', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('esewa', 'esewa'), ('khalti', 'khalti')], max_length=20, null=True)),
                ('order_redeem_code', models.CharField(max_length=500, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('payment_screen_short', models.ImageField(null=True, upload_to='payments/')),
                ('status', models.CharField(choices=[('Redeemed', 'Redeemed'), ('notRedeem', 'notRedeem'), ('notYetTime', 'notYetTime')], max_length=50, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('order_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crdOrder.product')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
