# Generated by Django 3.2.4 on 2021-07-12 15:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crdOrder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='redeemReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_redeem_code', models.CharField(max_length=500, null=True)),
                ('payOpt', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('esewa', 'esewa'), ('khalti', 'khalti')], max_length=50, null=True)),
                ('payToAdress', models.CharField(max_length=50, null=True)),
                ('payToName', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('redeemed', 'redeemed')], max_length=50, null=True)),
                ('Remark', models.TextField(max_length=150, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crdOrder.crdorder')),
            ],
            options={
                'verbose_name': 'Redeem Request',
                'verbose_name_plural': 'Redeem Requests',
            },
        ),
    ]
